In [3]:
import math
import numpy as np
import pandas as pd

class Customer:
    def __init__(self, location, demand):
        self.location = location
        self.demand = demand

def euclidean_distance(loc1, loc2):
    return math.sqrt((loc1[0] - loc2[0])**2 + (loc1[1] - loc2[1])**2)

def cost_matrix(customers):
    n = len(customers)
    cost_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(i+1, n):  # Iterate over upper triangular part only
            cost_matrix[i][j] = euclidean_distance(customers[i].location, customers[j].location)

    return cost_matrix

def savings_matrix(costs):
    n = len(costs)
    savings = np.zeros((n-1, n-1))

    for i in range(1, n-1):  # Skip the first and last rows (depot and last customer)
        for j in range(i+1, n):  # Skip the diagonal and lower triangle
            savings[i-1][j-1] = costs[0][i] + costs[0][j] - costs[i][j]

    return savings


# Define customers excluding the depot
customers = [
    Customer((0, 0), 0),        # The depot, starting point
    Customer((5, 14), 550),     # Customer 1
    Customer((10, 25), 400),    # Customer 2
    Customer((3, 30), 650),     # Customer 3
    Customer((35, 12), 250),    # Customer 4
    Customer((10, 7), 300)      # Customer 5
]
capacity = 1200

# Convert customers to DataFrame
customer_data = [(i, customer.location, customer.demand) for i, customer in enumerate(customers)]
df_customers = pd.DataFrame(customer_data, columns=['Customer', 'Location', 'Demand'])

# Drop the first row (depot) from the DataFrame
df_customers = df_customers.drop(0)

# Print customers DataFrame without row numbers and center-aligned
print(df_customers.to_string(index=False, justify='center'))
print("\nCapacity:",capacity,"\n")

# Calculate cost matrix
costs = cost_matrix(customers)

# Calculate savings matrix
savings = savings_matrix(costs)

# Flatten savings matrix and create list of (i, j, savings) tuples
savings_list = []
n = len(savings)
for i in range(n):
    for j in range(i+1, n):
        savings_list.append((i+1, j+1, savings[i][j]))  # Adjust indices to match customers' indices

# Sort savings list by savings value (in descending order)
savings_list.sort(key=lambda x: x[2], reverse=True)

# Print Cost Matrix
print("Cost Matrix:")
print(costs)
print()

# Print Savings Matrix
print("Savings Matrix:")
print(savings)
print("\n")

# Print sorted savings
print("Sorted Savings:\n")
for (i, j, saving) in savings_list:
    print(f"({i},{j}): {saving}","\n")


 Customer Location  Demand
    1      (5, 14)   550  
    2     (10, 25)   400  
    3      (3, 30)   650  
    4     (35, 12)   250  
    5      (10, 7)   300  

Capacity: 1200 

Cost Matrix:
[[ 0.         14.86606875 26.92582404 30.14962686 37.         12.20655562]
 [ 0.          0.         12.08304597 16.1245155  30.06659276  8.60232527]
 [ 0.          0.          0.          8.60232527 28.17800561 18.        ]
 [ 0.          0.          0.          0.         36.7151195  24.04163056]
 [ 0.          0.          0.          0.          0.         25.49509757]
 [ 0.          0.          0.          0.          0.          0.        ]]

Savings Matrix:
[[ 0.         29.70884681 28.89118011 21.79947599 18.4702991 ]
 [ 0.          0.         48.47312563 35.74781843 21.13237965]
 [ 0.          0.          0.         30.43450736 18.31455192]
 [ 0.          0.          0.          0.         23.71145805]
 [ 0.          0.          0.          0.          0.        ]]


Sorted Savings:

(2,3

In [14]:
import numpy as np
import pandas as pd

class Customer:
    def __init__(self, demand):
        self.demand = demand

def savings_matrix(costs):
    n = len(costs)
    savings = np.zeros((n-1, n-1))

    for i in range(1, n-1):
        for j in range(i+1, n):
            savings[i-1][j-1] = costs[0][i] + costs[0][j] - costs[i][j]

    return savings

# Define customers excluding the depot
customers = [
    Customer(0),    # starting point = College Station
    Customer(150),    # Navasota
    Customer(100),    # Hearne
    Customer(200),    # Huntsville
]
capacity = 200  # Kegs at a time

# Calculate cost matrix (All entries are the costs of driving between cities) [cost = distance * $4 per mile]
cost_matrix = np.array([[0, 4*24.2, 4*26.4, 4*52.2],
                        [0, 0, 4*46.8, 4*43.5],
                        [0, 0, 0, 4*73.5],
                        [0, 0, 0, 0]])

                        # Indices
                        # Row 1 & Column 1 = College Station
                        # Row 2 & Column 2 = Navisota
                        # Row 3 & Column 3 = Hearne
                        # Row 4 & Column 4 = Huntsville

# Calculate savings matrix
costs = cost_matrix  # Replace with actual cost calculation
savings = savings_matrix(costs)

# Flatten savings matrix and create list of (i, j, savings) tuples
savings_list = []
n = len(savings)
for i in range(n):
    for j in range(i+1, n):
        savings_list.append((i+1, j+1, savings[i][j]))

# Sort savings list by savings value (in descending order)
savings_list.sort(key=lambda x: x[2], reverse=True)

# Print Cost Matrix
print("Cost Matrix:")
print(costs)
print()

# Print Savings Matrix
print("Savings Matrix:")
print(savings)
print()

# Print sorted savings list
print("Sorted Savings List:")
for i, j, s in savings_list:
    print(f"({i}, {j}): {s}")


Cost Matrix:
[[  0.   96.8 105.6 208.8]
 [  0.    0.  187.2 174. ]
 [  0.    0.    0.  294. ]
 [  0.    0.    0.    0. ]]

Savings Matrix:
[[  0.   15.2 131.6]
 [  0.    0.   20.4]
 [  0.    0.    0. ]]

Sorted Savings List:
(1, 3): 131.60000000000002
(2, 3): 20.399999999999977
(1, 2): 15.199999999999989
